; MS41.3 Launch Control V5 soft-limiter enforcement cave.
;
; Entry: file 0x39DBC / CPU 0x3DDBC from file 0x247D2. Lower F014 only;
; it is regenerated by stock code every cycle. The V5 hard comparator at
; 0x39E20 independently uses LC_HARDRPM while leaving DB87 untouched.
base 0x3DDBC

        push DPP0
        push r4
        mov  DPP0,#4
        movb RL4,0xFD5A
        andb RL4,#0x40
        jmpr cc_EQ,done
        movb RL4,0x47E1               ; LC_CUTTYPE
        cmpb RL4,#0
        jmpr cc_NE,done
        movb RL4,0x47E3               ; LC_MAXRPM = launch soft limit
        cmpb RL4,0xF014
        jmpr cc_NC,done
        movb 0xF014,RL4
done:   pop  r4
        pop  DPP0
        bclr 0xFD5A.15                ; displaced MS41.3 instructions
        bclr 0xFD22.15
        jmps 0x0207D6
